### ISSUE TITLE
Failed to unpack

### ISSUE THREAD

**Issue by LevaniVashadze** [StopmotionSimonYT/QuoteTab#1]
![image](https://user-images.githubusercontent.com/100613979/186138459-92920137-d5b8-4fdc-a17d-b7c8888c3e47.png)
i downloaded this as zip. unzipped it and choosed the folder with all the files

**Comment by OpenSourceSimon** [comment]
Hi,
Thanks for using this project! I don't have that error but I think I can solve it.

**Comment by OpenSourceSimon** [comment]
Thanks for submitting the error! It should be fixed now, can you download it again?
